name: kaya
services:
  kaya:
    image: ghcr.io/sk3tchedlexi/kaya:latest
    container_name: kaya
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidia-modeset:/dev/nvidia-modeset
    privileged: true
    pid: host
    network_mode: host
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    labels:
      - "com.casaos.title=Kaya"
      - "com.casaos.description=A minimal self-hosted system dashboard"
      - "com.casaos.port=9783"
      - "com.casaos.scheme=http"
      - "com.casaos.index=/"
      - "com.casaos.icon=https://raw.githubusercontent.com/sk3tchedlexi/Kaya/main/Frontend/assets/brand/kaya-icon.svg"
